---
name: Python unit tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install `tox`
        run: python3 -m pip install tox
      - name: Run unit tests
        run: python3 -m tox -e py3 -- --cov --cov-report=term-missing --randomly-seed ${{ github.run_number }}
